baseURL = "https://sanazmhd.github.io/"
title = "Sanaz’s Blog"
theme = "PaperMod"
languageCode = "en-us"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Publish to /docs for GitHub Pages
publishDir = "docs"

[pagination]
pagerSize = 10000

# Silence theme warning
ignoreLogs = ['warning-partial-superfluous-prefix']

[params]
  ShowLangToggle = true
  ShowReadingTime = true

  # --- Social Icons ---
  [[params.socialIcons]]
  name = "GitHub"
  url  = "https://github.com/sanazmhd"

  [[params.socialIcons]]
  name = "LinkedIn"
  url  = "https://www.linkedin.com/in/sanaz-mhd/"  # ← replace with your LinkedIn URL

  [[params.socialIcons]]
  name = "Instagram"
  url  = "https://www.instagram.com/saanazm"  # ← replace with your Instagram URL

  [[params.socialIcons]]
  name = "Google Scholar"
  url  = "https://scholar.google.com/citations?user=YOUR_ID"  # ← replace with your Scholar page

  [[params.socialIcons]]
  name = "CV"
  url  = "/files/cv.pdf"   # ← put your CV at static/files/cv.pdf

# -----------------------------
# Languages
# -----------------------------
[languages]

  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    title = "Sanaz’s Blog"

    [languages.en.params]
      homeInfoParams = { Title = "Welcome to my blog", Content = "I’m Sanaz. This blog is my personal space to share interesting things with you — from tutorials, books, and music to tech and language learning." }

    # --- Top Navigation ---
    [[languages.en.menu.main]]
      identifier = "learning"
      name = "Learning"
      url = "/learning/"
      weight = 1

  [languages.fa]
    languageName = "فارسی"
    weight = 2
    contentDir = "content/fa"
    title = "وبلاگ ساناز"
    languagedirection = "rtl"

    [[languages.fa.menu.main]]
      identifier = "learning"
      name = "یادگیری"
      url = "/fa/learning/"
      weight = 1

# Allow raw HTML in Markdown (for dropdown menus, embeds, etc.)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

